apiVersion: v1
kind: Service
metadata:
  name: windows-iis
  labels:
    app: windows-iis
spec:
  selector:
    app: windows-iis
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
