apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-frontend
  namespace: hybrid-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linux-frontend
  template:
    metadata:
      labels:
        app: linux-frontend
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: frontend
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: linux-frontend
  namespace: hybrid-lab
spec:
  selector:
    app: linux-frontend
  ports:
    - port: 80
      targetPort: 80
