apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: hybrid-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: redis
          image: redis:7.4
          ports:
            - containerPort: 6379
